INSERT INTO TBL_BUY (custom_id,PCODE,QUANTITY,BUYNO)
VALUES ('mina012','IPAD011',1,tbl_buy_seq.nextval);

SELECT * FROM TBL_BUY tb ;

DELETE FROM TBL_BUY tb  WHERE CUSTOM_ID = 'sana97';
DELETE FROM TBL_CUSTOM tc WHERE CUSTOM_ID = 'sana97';

SELECT * FROM TBL_CUSTOM tc ;
SELECT * FROM TBL_BUY tb ;

ROLLBACK;

ALTER TRIGGER secure_custom disable;
UPDATE TBL_CUSTOM SET EMAIL = 'test@gmail.com'
WHERE CUSTOM_ID = 'twice';

SELECT * FROM TBL_CUSTOM tc ;