-- tbl_custom 참조하는 외래키 삭제
ALTER TABLE tbl_buy DROP CONSTRAINT TBL_BUY_FK;

ALTER TABLE TBL_BUY ADD CONSTRAINT fk_custom_id
	FOREIGN KEY (CUSTOM_ID)
	REFERENCES tbl_custom(CUSTOM_ID)
	ON DELETE CASCADE;
